### ISSUE TITLE
맵에 있는 구석자리에 들어가서 어찌저찌하면 맵 바깥으로 나가지는 이슈

### ISSUE THREAD

**Issue by KMJ1324** [notdevblue/GangsterHamster#113]
믕

**Comment by notdevblue** [comment]
이거 컬라이더 이슈임
벽쪽 컬리이더 모서리 닿는 부분 늘려서 모서리하고 모서리가 만나는게 아니라 모서리하고 면이 만나야 함

대충

ㅁ
 ㅁ

에서
ㅁㅁ
 ㅁ

으로 하면 해결됨

**Comment by notdevblue** [comment]
#134 중복?
