### ISSUE TITLE
문 관련 이슈들

### ISSUE THREAD

**Issue by jeesung0822** [notdevblue/GangsterHamster#124]
- 루모 효과를 받은 상태에서 접근하면 열리는 문에 비비면 뒤로 끌어당겨짐

- 접근하면 열리는 문의 플레이어를 인식하는 범위를 현재보다 1.5배 이상 넓혀주세용

- 문들 전체적으로 열려있는 상태일 때 안쪽 문이 바깥으로 튀어나와있는 현상

**Comment by notdevblue** [comment]
뒤로 끌어당겨지는거 재현이 안됨
+ 아레 두개는 스테이지 갈아엎을 때 해결할 예정
