### ISSUE TITLE
루모 발사 안되는 버그

### ISSUE THREAD

**Issue by jeesung0822** [notdevblue/GangsterHamster#145]

**Comment by KMJ1324** [comment]
루모 발사가 안되는 상황 또는 원인을 확실하게 써주신다면 고치는데 큰 도움이 될 거 같아요...
원인이 뭔지 알기 힘들어서 고치기 힘들어져요

**Comment by jeesung0822** [comment]
앗 이거 예전에 Atype을 향해 루모를 발사해도 날아가지 않는 버그였는데 지금은 고쳐져있네요

**Comment by KMJ1324** [comment]
그렇쿤쵸
