### ISSUE TITLE
루모 능력이 안 써지는 듯 함 + 색수차 효과 널레퍼런스

### ISSUE THREAD

**Issue by notdevblue** [notdevblue/GangsterHamster#160]
### 능력 관련
루모스테이지 프론트에서 능력이슈 겪음
*다른곳에서도 그러는지는 모르겠지만*

* * *
### 색수차 관련
루모 능력 볼륨에 색수차 말고 모션블러만 들어가있음
\+ 이거 고치면서 볼륨 이름도 바꿔줘요

**Comment by KMJ1324** [comment]
넴 고쳤서요
