### ISSUE TITLE
카메라 애니메이션 (리스트업)

### ISSUE THREAD

**Issue by jeesung0822** [notdevblue/GangsterHamster#171]
[ 카메라 이펙트 리스트업 ]

- 걸을 때
- 충돌했을때 셰이킹 
- 착지했을때 바운드 (살짝만) (4m 이상의 높이에서 떨어질 때만)
- 죽을 때 화면 고정하고 채도 낮추기 + 초점 흐리기
- 루모 효과 적용 시 FOV 넓히기
- 앉을 때 & 일어날 때 자연스럽게
- 반동 받을 때

**Comment by junff001** [comment]
다 만듦 ㅋ

**Comment by junff001** [comment]
ㄹㅇ 다 만듦
