### ISSUE TITLE
퀄리티 업 작업들 (리스트업)

### ISSUE THREAD

**Issue by jeesung0822** [notdevblue/GangsterHamster#172]
- 그랜드로 버튼 여러개를 동시에 누를 때 개선
- 도구 교체 연출
- 그랜드 Lv.2, Lv3일 때 카인의 안쪽 민트색 구는 회전하고 겉면은 파편으로 나뉘어 중심을 기준으로 회전
- 그라비토의 카인 크기 조금만 더 키우기
- 그라비토 UI 그랜드 UI랑 같은걸로 교체 (동그란 원 UI)
- 도구 회수 시 사라지는 이펙트 및 손에 드는 이펙트 추가

작업 완료 된 것들은 댓글로 달아주세요
설명 혹은 레퍼런스가 필요하다면 말해주세요

**Comment by KMJ1324** [comment]
그랜드 버튼 문제 진짜 해결 되었음
도구 교체 연출은 쉽지 않아 보여서 일단 안한다는 생각
그랜드 lv2, lv3 때 도는 연출도 확실히 필요한게 아니라서 보류
그라비토 카인은 키웠고
UI 같은거로 교체는 확실하게 이해를 못했음
회수시 사라지는 이펙트는 없지만 손에 드는 이펙트는 조금이나마 어떻게 되기는 함

**Comment by notdevblue** [comment]
일단 이거 클로즈 해 두겠슴.
