### ISSUE TITLE
그랜드 비활성화 해도 그랜드가 나타남

### ISSUE THREAD

**Issue by notdevblue** [notdevblue/GangsterHamster#192]

**Comment by KMJ1324** [comment]
정보가 부족해요
무슨말인지 확실하게 알 수 있도록 더욱 자세하게 부탁해요

**Comment by notdevblue** [comment]
그랜드 Possible use 체크를 해제하고 루모만 활성화했지만 그랜드를 든 상태로 시작되고
루모를 들어도 그랜드가 비활성화 되지 않음

**Comment by notdevblue** [comment]
Weapon Management의 Start Handle Weapon 수정 안한 문제
