### ISSUE TITLE
맵 라이팅 및 색상 관련

### ISSUE THREAD

**Issue by jeesung0822** [notdevblue/GangsterHamster#200]
그랜드, 그라비토 맵 전반적으로 어두움
플레이 상 중요하지 않은 빛들의 밝기가 너무 강함
→ 플레이에 핵심이 되는 오브젝트들이 상대적으로 잘 안보임 (출구, 큐브 등)
→ 중요하지 않은 빛들은 밝기를 낮추고 핵심 오브젝트들은 강조되게 해야 함 (+ 출구 더 강조하기)

버튼·스위치·연결선의 비활성 색상이 붉은색이라 플레이어 입장에서 위협적인 오브젝트로 인지하는 듯
→ 회색으로 바꿔보는건 어떨까
 , 레이저를 붉은색으로 바꿔보기

**Comment by notdevblue** [comment]
맵 재작업과 겹치는 이슈
