### ISSUE TITLE
스테이지 관련 자잘한 이슈들

### ISSUE THREAD

**Issue by jeesung0822** [notdevblue/GangsterHamster#204]
그랜드 5 - 문이 버튼을 누르지 않아도 접근하면 열림
그랜드 7 - 회전하는 큐브 속도 낮추기
그랜드 9 - 스위치랑 레이저 간 연결이 제대로 안맞은듯
그랜드 10 - 그랜드 올라타서 앉는 부분 레이저 없애기
그라비토 2 - 벽에 조금 삐져나온 EXIT때문에 헷갈림 안보이게 가려줘야 함
그라비토 5 - 문위치가 잘못된듯?, 유리 다이얼로그 넣기
그라비토 6 - 콜라이더 없는 부분 넣기
그라비토 8 - 못 깸, 맵수정 필요
루모 8 - 콜라이더 잘못 넣은 부분 있음, Atype 벽인데 Atype으로 인식이 안되는 부분 있음
루모 10 - 앞부분 레이저 다 빼기, 좌우 이동하는 레이저 배치가 잘못됨, 스위치 넣기, 뒷부분 유리 높이 수정

**Comment by jeesung0822** [comment]
이거 작업할 때 모르는거 물어보세영

**Comment by KMJ1324** [comment]
루모 10 제외 모두 수정 완료 
루모 10은 다른 이슈로 등록할게요
