### ISSUE TITLE
튜토리얼 관련 버그

### ISSUE THREAD

**Issue by KMJ1324** [notdevblue/GangsterHamster#207]
그랜드 튜토리얼 같은 경우에 생각보다 자주 버그가 발생했음
다이얼볼륨 바깥에서 이미 무기를 발사하고 나서 볼륨 안으로 들어가면 문제가 발생하는 경우나
사용자가 다이얼로그대로 행동하지 않고 다른 행동을 하게 되면 꼬이게 되서 앞으로 못 넘어가는 상황이 발생하는 경우가 많았음

**Comment by notdevblue** [comment]
다이얼로그와 타임라인 작업으로 해결됨
