### ISSUE TITLE
A타입 큐브 리젠 시스템

### ISSUE THREAD

**Issue by notdevblue** [notdevblue/GangsterHamster#213]
루모 8스테이지처럼 A타입 큐브가 낭떠러지로 떨어지거나 등등의 이슈로 큐브에 접근할 수 없을때를 위한 리젠 시스템이 필요할 거 같음

**Comment by KMJ1324** [comment]
기능은 생겼어요
이제 스테이지에 적용을 하면 작동 할거에요

**Comment by KMJ1324** [comment]
어 close는 하면 안되는데
