### ISSUE TITLE
스테이지 와 스테이지를 이어주는 작은 공간 천장에 컬라이더 없음 (사진 꼭 확인하기)

### ISSUE THREAD

**Issue by junff001** [notdevblue/GangsterHamster#219]

**Comment by notdevblue** [comment]
조금 자세하게 써주셈

**Comment by junff001** [comment]
![image](https://user-images.githubusercontent.com/71419212/190985095-e9167857-cd3e-47e3-b13a-69dc87e56364.png)
이 부분 컬라이더가 없습니다
