### ISSUE TITLE
루모 능력 버그

### ISSUE THREAD

**Issue by notdevblue** [notdevblue/GangsterHamster#233]
**Describe the bug**
루모 능력을 활성화했지만 한번 나갔다 들어와야 적용이 되는 버그

**To Reproduce**
1. 루모 능력을 활성화
2. 루모 능력 영향 범위에 들어감
3. 루모 무기 비활성화
4. 다시 루모 무기 능력 활성화
5. See Error

**Expected behavior**
정상적으로 잘 작동할 것이라고 생각함

**Additional context**
아마도 InteractableObjects 수정 이후로 이러는거 같음
한번 확인해줘요

@KMJ1324

**Comment by KMJ1324** [comment]
고친거같은
