### ISSUE TITLE
카메라 착지 효과 이슈

### ISSUE THREAD

**Issue by KMJ1324** [notdevblue/GangsterHamster#237]
**Describe the bug**
착지 시 카메라가 천천히 아레로 내려가고 쓲 올라감
그리고 transform.localPosition assign attempt for 'PLAYER_CAM' is not valid. Input localPosition is { 0.000062, NaN, 0.000000 }. 뜸

**To Reproduce**
1. 일반적인 카메라 착지 효과 재생을 보면 됨

**Expected behavior**
부드럽게 쌰악 하고 내려갔다가 올라오는 거

**Additional context**
병합 할때 꼭 버그 확인하고 올리셈
- 우앱

**Comment by junff001** [comment]
안 고쳐

**Comment by junff001** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by junff001** [comment]
고칠게요

**Comment by junff001** [comment]
고쳤어요
인스펙터에 변수 하나가 0 이였네 허허
