### ISSUE TITLE
그랜드가 바닥을 따라가지 않음

### ISSUE THREAD

**Issue by notdevblue** [notdevblue/GangsterHamster#239]
**Describe the bug**
제곧네

**To Reproduce**
1. 바닥을 보고 점프하며 그랜드 발사
2. See error

**Expected behavior**
스므스하게 그랜드가 바닥과 같이 이동을 할 줄 알았음

**Comment by notdevblue** [comment]
이거 바닥을 보고 점프하며 그랜드 발사해도 가끔 일어나는 버그라 버그 재현이 안됨

@개발 도움!

**Comment by KMJ1324** [comment]
일단은 내가 예전에 발견한 조건은 해결 확실히 된 거 같으니 Close
