### ISSUE TITLE
카메라 보정 기능

### ISSUE THREAD

**Issue by notdevblue** [notdevblue/GangsterHamster#240]
지금 카메라가 아무런 보정 없이 좌우 흔들려서 게임 화면이 보기 조금 그럼

그래서 어느 한 위치에 카메라가 바라보는 쪽을 고정하는 그러한 스크립트가 필요할 거 같스빈다.

[대충 여기 예시가 있음](https://youtu.be/5MbR2qJK8Tc)

**Comment by notdevblue** [comment]
*필요없을수도*

**Comment by junff001** [comment]
컷
