### ISSUE TITLE
그랜드 사운드 이슈

### ISSUE THREAD

**Issue by notdevblue** [notdevblue/GangsterHamster#242]
**Describe the bug**
플레이어가 그랜드를 들고 있는 상태에서 그랜드가 벽이나 그러한 물체에 Collision 또는 Trigger 할 시 충돌 사운드가 재생됨

**To Reproduce**
1. 그랜드를 들고 무기를 벽 등에 닿아서 통과되게 함
2. See Error

**Expected behavior**
아무런 소리 안 나는거로 예상함

**Comment by KMJ1324** [comment]
소리 수정 된 듯 해요
