### ISSUE TITLE
(fix/FollowGroundPos) 그랜드 스케일이 커짐에 따라 플레이어 스케일도 영향을 받음

### ISSUE THREAD

**Issue by notdevblue** [notdevblue/GangsterHamster#245]
그랜드 위에 플에이어가 서 있을때 스케일을 조절하면
자식으로 들어간 플레이어 스케일도 조절되서
결국 미친 크기의 플레이어가 탄생함

=> OnChangeEnd(); 하나만 만들어줘요

**Comment by KMJ1324** [comment]
그 뭐냐 이벤트 GrandMessageBroker 에 추가했으니까 확인해줘요
