### ISSUE TITLE
낮은 해상도에서 UI가 삐져나가는 이슈

### ISSUE THREAD

**Issue by notdevblue** [notdevblue/GangsterHamster#253]
**Describe the bug**
설정 같은 창이 1920x1080 이하 사이즈에서 밖으로 삐저나감

**To Reproduce**
1. FHD 보다 낮은 해상도로 ㄱ
2. See error

**Expected behavior**
일반적으로 사이즈가 통일될 거 같았음

**Comment by KMJ1324** [comment]
수정 된거 같은
