### ISSUE TITLE
볼륨 동기화 이슈

### ISSUE THREAD

**Issue by notdevblue** [notdevblue/GangsterHamster#254]
**Describe the bug**
ESC 메뉴로 들어가기 전에는 볼륨이 1로 고정됨.

**To Reproduce**
1. 게임 실행
2. 소리 재생
3. See error
4. ESC 매뉴 진입
5. ESC 매뉴 탈출
6. 정상 작동

**Expected behavior**
6단계가 3단계에서 작동할 줄 암

**Additional context**
이상하게 귀가 아프더라

**Comment by KMJ1324** [comment]
이론상 성공
