### ISSUE TITLE
그라비토 능력 사용 중 스테이지를 클리어하면 사운드가 계속 재생됨

### ISSUE THREAD

**Issue by notdevblue** [notdevblue/GangsterHamster#255]
**Describe the bug**
재곧내

**To Reproduce**
1. 그라비토 사용
2. 스테이지 클리어
3. See error

**Expected behavior**
능력 사운드가 끝날 줄 알았음

**Comment by notdevblue** [comment]
튜토 스테이지에서 발생함

**Comment by junff001** [comment]
정상작동 하는데요?
(음.. 이것도 사운드 채널 문제인가..)

**Comment by junff001** [comment]
일단 이슈 Close 안할게요

**Comment by KMJ1324** [comment]
수정함
