### ISSUE TITLE
Grand 에 카메라 끼임 현상

### ISSUE THREAD

**Issue by junff001** [notdevblue/GangsterHamster#261]
**Describe the bug**
Grand가 커지는 도중에 그 위로 착지하면 카메라가 끼이고 현상이 영구 반영되는 버그입니다.
**To Reproduce**
1. Grand 를 최동단계까지 키운다.
2. Grand 가 커지는 도중에 그 위로 착지한다.
3. 카메라가 Grand에 끼인다.
4. Grand 를 회수한다.
5. 플레이어, 카메라 모두 아래로 꺼진 현상을 마주한다.

**Expected behavior**
끼면 안되고 플레이어, 카메라 모두 아래로 꺼지면 안됩니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/71419212/192767968-198056e1-5774-4da6-9940-1935adffff71.png)
![image](https://user-images.githubusercontent.com/71419212/192768026-bf6841c5-6a2f-4630-bab3-3fc7ad41d3d0.png)

**Comment by notdevblue** [comment]
이거 내 이슈일수도

**Comment by junff001** [comment]
오.....

**Comment by junff001** [comment]
우엽 이거 혹시 고침??

**Comment by notdevblue** [comment]
아직 안 고침

**Comment by junff001** [comment]
오늘 하니까 버그가 재현이 안되네

**Comment by notdevblue** [comment]
내이슈 맞네 이런

**Comment by notdevblue** [comment]
아마 고처짐
