### ISSUE TITLE
카메라 흐려짐 무한 지속 버그

### ISSUE THREAD

**Issue by jeesung0822** [notdevblue/GangsterHamster#271]
**Describe the bug**
그랜드 반동 받을 때 흐려짐 효과가 무한 지속되는 버그

**To Reproduce**
1. 그랜드의 반동을 받자마자(흐려진 상태) 레이저에 닿기
![image](https://user-images.githubusercontent.com/69909293/192954149-4087bbf2-277c-40e4-9643-592eef2cef7c.png)
2. 갬성있는 게임 가능

**Comment by junff001** [comment]
!

**Comment by junff001** [comment]
문제해결
