### ISSUE TITLE
스위치 E 시전하면 무기 사라짐

### ISSUE THREAD

**Issue by notdevblue** [notdevblue/GangsterHamster#274]
**Describe the bug**
아마 잡기 판정 나서 그런 버그인듯 함

**To Reproduce** (예시)
1. 그랜드 듬
2. E 누름
3. 그랜드 증발
4. 다시 E 누르면 돌아옴

**Comment by KMJ1324** [comment]
이건 그 스위치가 static이 아닌 이슈 같은데 지금 테스트 햇을 때는 위와 같은 문제를 본 적이 없는거 같애요
그래서 문제가 있었던 씬 정확히 올려주시면 확실한 원인을 알 수 있을 듯 해요
