### ISSUE TITLE
플레이어가 길어지는 이슈 - 버튼집 뚫리는 버그와 연계됨

### ISSUE THREAD

**Issue by KMJ1324** [notdevblue/GangsterHamster#278]
**Describe the bug**
특정 위치에서 그라비토 능력을 발동시 플레이어의 높이가 괴상하게 변환하는 오류

**To Reproduce**
- 그라비토 3스테이지 씬에서 발생

1. 그라비토 능력을 발동
2. 버튼 상자? 그 안으로 들어 간 뒤 대각선 위치로 이동
3. R을 통해 무기 회수
4. 이러면 벽뚫 오류가 발생함
5. 그 상태에서 투명 벽 쪽으로 무기를 발사 후 능력을 발동
6. See error - 플레이어 Y Scale 이 매우 커짐

**Expected behavior**
1. 벽이 뚫리지 않고 정상적으로 중력이 변환됨
2. 투명 벽에 능력 발동시 플레이어가 정상적인 상태로 중력이 변환 됨

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/70933806/193802310-b27ef090-7799-4ee6-98c4-74d50b81e50e.png)
> 저거 기다란 회색 선 플레이어임

**Additional context**
물론 그라비토로 버튼 블럭 벽이 뚫리는 버그를 수정시 해결되는 문제지만, 
지금 발견한 버그가 다른 상황에서 다시 발생 할 수 있으므로 등록

**Comment by notdevblue** [comment]
스케일 이슈는 고침
그런데 벽뚤은 그라비토 회수할때 플레이어 로테이션 돌리는 거랑 관련이 있어서 @KMJ1324

**Comment by notdevblue** [comment]
버튼하우스에 레이저 넣은거 푸쉬한거같으니까 닫음
