### ISSUE TITLE
사운드 밀림 현상 

### ISSUE THREAD

**Issue by junff001** [notdevblue/GangsterHamster#279]
**Describe the bug**
간혹 이벤트로 발생하는 사운드가 딜레이 되어 재생됩니다. (예 : 유리 꺠짐 사운드)

**To Reproduce**
1. 유리는 깬다.
2. 몇 초 후에 유리 깨짐 사운드가 발생하는 현상을 마주한다.

**Expected behavior**
달레이 없이 즉각적으로 사운드가 발생해야함

**Additional context**
위 방법대로 하더라도 사운드 딜레이 현상이 나타는 경우가 있습니다. 하지만 이 현상은 빌드 후에 언제든지 재발현 될 수 있는 버그 입니다. 그렇기에 사운드 매니저를 활용하여 사운드 채널을 분리시켜 놔야합니다. (준무 쌤 조언)

**Comment by junff001** [comment]
이거 지금 너무 애매한 거 같으니까 나중에 해결하세요

**Comment by KMJ1324** [comment]
하지만 이미 해결해버린
