### ISSUE TITLE
3D Sound Merge 로 인한 사운드 스크립트 이슈

### ISSUE THREAD

**Issue by notdevblue** [notdevblue/GangsterHamster#289]
**Describe the bug**
3D Sound Merge 로 Meta 파일 이슈가 생겨서
사운드 관련 스크립트가 전부 Missing 뜸
네. 깃 터지는것보단 훨 고치기 쉬운 이슈입니다.

**Additional context**
이걸머지했네

**Comment by junff001** [comment]
^^7;;;

**Comment by notdevblue** [comment]
커밋 삭제당함
